version: '3.10'

services:
  hub:
    container_name: hub
    image: selenium/hub
    ports:
      - '4444:4444'
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  allure-report-service:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 0
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports